Lesson5
AlexandrKachan/TMS_110121 pull request #1
Opened 2021-01-28 15:43 UTC by AlexandrKachan

В начале идет пример из урока, далее задачи от  9 до 12 по методичке. Задачи по циклам.

2021-01-29 05:53 UTC, yurachel commented on Lesson_5/src/com/cycles/exercise10.java
> +        // Посчитать факториал числа в границах от 10 до 15
факториал числа 10 будет 1*2*3*4*5*6*7*8*9*10.
Ну и так далее для каждого числа до 15

2021-01-29 06:13 UTC, yurachel approved these changes

2021-01-29 06:13 UTC, YuryFarshyniou commented on Lesson_5/src/com/cycles/exercise10.java
> +        // Посчитать факториал числа в границах от 10 до 15
https://math-prosto.ru/?page=pages/factorial/factorial.php

2021-01-29 06:13 UTC, yurachel commented on homework_pullRequests/src/com/karinaleonova/task12.java
> +        for (int i = 1; k <= 12; i++) {
Можно было k не добавлять даже,поставить просто i<=12 и было бы ок

2021-01-29 08:55 UTC, yurachel approved these changes

2021-01-29 17:34 UTC, RomanKashenok requested changes

2021-01-29 17:34 UTC, RomanKashenok commented on Lesson_5/src/com/cycles/cyclesRunner.java
>  public class cyclesRunner {
Remove this file from PR

2021-01-29 17:34 UTC, RomanKashenok commented on Lesson_5/src/com/cycles/exercise10.java
> +            System.out.println(" произведение = " + a);
10! should be equal to  3628800
11! - 39916800
and ctr. you just multiplying numbers and I don't know how this operation should ba called :)

2021-01-29 17:34 UTC, RomanKashenok commented on Lesson_5/src/com/cycles/exercise11.java
> +            System.out.println(" число c = " + c);
remove this intermediate outs.

2021-01-29 17:34 UTC, RomanKashenok commented on Lesson_5/src/com/cycles/exercise11.java
> +        while (d < number) {
A lot of unnecessary statements. You just need 2 variables - first is your number and second - counter.

2021-01-29 17:34 UTC, RomanKashenok commented on Lesson_5/src/com/cycles/exercise12.java
> +        System.out.println("число " + number);
1. Too complicated
2. Not correct. If I need to get sum of first 3 numbers that could be devided on 3 I expect to get 18 (3 + 6 + 9). But in your case I'll get 3 as a result. Correct please

2021-01-29 17:34 UTC, RomanKashenok commented on Lesson_5/src/com/cycles/exercise9.java
> +//
remove comments

2021-01-29 17:34 UTC, RomanKashenok commented on Lesson_5/src/com/cycles/exercise9.java
> +        int y= 4;
what means 'y' ? what is the purpose of this variable? What name 'y' should told me?

2021-01-29 17:34 UTC, RomanKashenok commented on Lesson_5/src/com/cycles/exercise9.java
> +    }
I even don't understand what this code doing...

2021-01-29 17:34 UTC, RomanKashenok commented on homework_pullRequests/src/com/karinaleonova/task12.java
> +package com.karinaleonova;
палево )))

2021-02-01 04:56 UTC, yurachel approved these changes

2021-02-01 06:49 UTC, yurachel commented on Lesson_5/src/com/cycles/exercise10.java
> +            a = a*b;
Это не то ,ты просто сначала 10*10,потом 100 *11 и так далее,это не факториал.

2021-02-01 08:39 UTC, yurachel requested changes

2021-02-01 08:39 UTC, yurachel commented on Lesson_5/src/com/cycles/exercise10.java
> +        while (b <= c) {
Так здесь же все равно не то.

2021-02-12 08:05 UTC, AlexandrKachan commented
Исправил все замечания.

2021-02-13 15:18 UTC, RomanKashenok requested changes

2021-02-13 15:18 UTC, RomanKashenok commented on Lesson_5/src/com/array/exercise16.java
> +        for (int i = 0; i < array.length; i++) {
а не проще пройтись от индеса минимального(или максимального) до индекса максимального(или минимального)?
Если у тебя последовательность из 1,2,3,4,5,100,2,3,4,3,5,3,5,6,3 и так еще 100500 чисел меньше 100, зачем тебе пробегать весь массив еще раз, если ты знаешь, что минимальное на 0 позиции, а максимальное на 5й ?

2021-02-13 15:18 UTC, RomanKashenok commented on Lesson_5/src/com/array/exersice15.java
> +            if (i == arr.length / 2) break;        // пока длинна масива не больше его половины
это условие можно поместить в блок for:
for (int i = 0; i < arr.length/2; i++)

2021-02-13 15:18 UTC, RomanKashenok commented on Lesson_5/src/com/cycles/exercise10.java
> +        int b = a;
int a,b = 1; так понятнее

2021-02-13 15:18 UTC, RomanKashenok commented on Lesson_5/src/com/cycles/exercise9.java
> +//        double averageSum = 0;
убирай комментарии из пул реквестов

2021-02-13 15:18 UTC, RomanKashenok commented on homework_pullRequests/src/com/karinaleonova/task12.java
> +        for (int i = 1; k <= 12; i++) {
а почему 12?

2021-02-19 08:20 UTC, merged